### ISSUE TITLE
Long response time when "cold"

### ISSUE THREAD

**Issue by keligijus** [aaparmeggiani/towerbridge#1]
Hey, great API, thanks for creating and making it public. I'm using your API to build an Alexa Skill.

I've noticed that whenever I call any endpoint for the first time, it does not respond within 6000ms. 6000ms is the timeout limit for AWS Lambda, which I'm using to fetch data from your API.

Just wondering if there's anything we can to keep it active? Is it because Heroku needs to do some magic before your code runs for the first time?

For now, I'll probably be setting a cron job to keep your API "warm". I hope that's ok :)

**Comment by aaparmeggiani** [comment]
Thanks for your feedback; nice to see it’s being helpful somehow.   The delay is expected as, on a free tier, Heroku puts your free dyno to sleep after 30m of inactivity and there is a time to wake it up. 

The cron job would solve the warm-up problem but the free dyno allowance is 550h/month, what would make the API unavailable after 23 days running non stop.  You could try letting it sleep at night (link below)  but final solution would be a hosting without that limitation.  

https://medium.com/@pandachain/keep-free-heroku-app-awake-during-a-specific-period-using-google-app-script-in-2017-63fe37ee9e9f

**Comment by keligijus** [comment]
Got it. Thanks for a prompt reply :)

I'm going to use your solution to keep the API awake during daytime.

**Comment by aaparmeggiani** [comment]
Cool, thanks.  Would you mind if I add your Alexa Skill to the Readme page ?

**Comment by keligijus** [comment]
That would be awesome :) Here's a [link](https://www.amazon.co.uk/EligijusKrepsta-Tower-Bridge-Lift-Times/dp/B078RPHXD2/) to the skill on Alexa store.

I'd love to credit your work on the skill readme too. Should I write anything specific?

**Comment by aaparmeggiani** [comment]
Already there, under "using the API.."    

Hmm, not sure how that works in Alexa's world.  In Apps, apis/open_source are usually mentioned  under an about/credits screen in the  app, but not in the app_store/description.  Once the Skills don't have a visual interface  I'm not sure where it should go.  Anyway, feel free to add it (or not)  and thanks for building the skill.  It was really cool to "hear" it working ;-)

**Comment by keligijus** [comment]
Thanks!

I'm still in a discovery process. I'll probably add a reference to the description :)
