### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by jackjury** [aaparmeggiani/towerbridge#2]
Hello, 

It looks like the API is currently down, it is returning this error:

> Unable to fetch data: redirection forbidden: http://www.towerbridge.org.uk/lift-times/ -> https://www.towerbridge.org.uk/lift-times/

It looks like this is a result of the website owner switching to an SSL connection.  Can we update this?

Thanks, 

Jack

**Comment by aaparmeggiani** [comment]
Thanks Jack, and sorry for leaving it open for soooo long.
I deprecated the old code in favor of having updated json files on github.
Cheers!
